# Reference: https://docs.docker.com/compose/compose-file/compose-file-v3
#
# Note: requires docker-compose v1.28.0+
---
version: "3.4"

services:
  # Simulation
  webots_simulation:
    build:
      context: .
      dockerfile: Dockerfile.Webots
      network: host
    command: bash -c ". /entrypoint.sh create2_description spawn_robot.launch.py"
    container_name: webots_simulation
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    devices:
      - /dev/snd
      - /dev/dri
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    #network_mode: "host"
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user: create2
    volumes:
      - /home/$USER/colcon_ws/src/create2_description:/colcon_ws/src/create2_description:rw
      # TODO: We have our own copy of webots_ros2 with changes
      - /home/$USER/colcon_ws/src/webots_ros2:/colcon_ws/src/webots_ros2:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /colcon_ws

  # Robot hardware
  hardware:
    image: osrf/ros:foxy-desktop
    command: bash -c ". /entrypoint.sh create2_hardware standalone.launch.py"
    container_name: hardware
    devices:
      - /dev/usb
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /home/$USER/colcon_ws/src/create2_hardware:/colcon_ws/src/create2_hardware:rw
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /colcon_ws

  # Software stack
  autonomy:
    image: osrf/ros:foxy-desktop
    command: bash -c ". /entrypoint.sh create2_vision pointcloud.launch.py"
    container_name: autonomy
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /home/$USER/colcon_ws/src/create2_autonomy:/colcon_ws/src/create2_autonomy:rw
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /colcon_ws

  # Development
  # docker-compose run --rm dev
  dev:
    image: osrf/ros:foxy-desktop
    command: /bin/bash
    container_name: dev
    depends_on:
      - webots_simulation
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /home/$USER/colcon_ws:/colcon_ws:rw
      - ./entrypoint.sh:/entrypoint.sh
    working_dir: /colcon_ws

