# Reference: https://docs.docker.com/compose/compose-file/compose-file-v3
#
# Note: requires docker-compose v1.28.0+
---
version: "3.4"

services:
  webots_simulation:
    build:
      context: .
      dockerfile: Dockerfile.Webots
    command: bash -c "cd /colcon_ws && colcon build && . /colcon_ws/install/setup.bash && ros2 launch create2_description spawn_robot.launch.py"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: webots_simulation
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
    devices:
      - /dev/snd
      - /dev/dri
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    network_mode: "host"
    privileged: true
    user: create2
    volumes:
      - /home/$USER/colcon_ws:/colcon_ws:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /colcon_ws

  hardware:
    image: osrf/ros:foxy-desktop
    command: bash
    container_name: hardware
    devices:
      - /dev/dri
      - /dev/snd
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    privileged: true
    user: root
    tty: yes # Without a tty, rclpy/rclcpp infinitely buffer standard out
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

